---
title: "R Notebook"
author: admin
date: 3/27/2021
output: html_document
---
```{r}
library(text2vec)
library(jsonlite)

data <- read_json("Indeed_data/indeed_job_descs_2021_01_25.json")
```
```{r}
library(stringr)

indeed_iterate_data <- function(data, callback)
{
  for (row in data)
  {
    job_location <- row$request_params$l
    job_time <- row$request_params$jt
    job_title <- row$request_params$q

    job_ids <- names(row$job_descriptions)

    for (i in seq_along(row$job_descriptions))
    {
      job_id <- job_ids[i]
      job_desc <- row$job_descriptions[i][[1]]

      callback(job_location, job_time, job_title, job_id, job_desc)
    }
  }
}


indeed_iterate_files <- function(callback)
{
  for (fpath in list.files(path = "Indeed_data", pattern = "*.json", full.names = TRUE))
  {
    data <- read_json(fpath)
    indeed_iterate_data(data, callback)
  }
}


indeed_csv_row_count <- function()
{
  row_count <- 0
  indeed_iterate_files(
          function(job_location, job_time, job_title, job_id, job_desc)
          {
            row_count <<- row_count + 1
          }
  )
  row_count
}


indeed_csv_build <- function(output_file)
{
  row_count <- indeed_csv_row_count()

  CSV_NA <- ""
  CSV_COLUMNS <- c('job_location', 'is_fulltime', 'is_parttime', 'is_contract', 'is_internship', 'salary_min', 'salary_max', 'job_title', 'job_id', 'job_desc')
  REGEX_JOB_TIME <- "Job Type(Full-time|Part-time|Contract|Internship){1,3}"
  REGEX_SALARY_RANGE <- "\\$([\\d,]+)\\s*-\\s*\\$([\\d,]+)"

  df <- data.frame(matrix(ncol = length(CSV_COLUMNS), nrow = row_count))
  colnames(df) <- CSV_COLUMNS

  row_index <- 1

  indeed_iterate_files(
          function(job_location, job_time, job_title, job_id, job_desc)
          {
            csv_row <- as.list(rep(CSV_NA, length(CSV_COLUMNS)))
            names(csv_row) <- CSV_COLUMNS

            # parse job time
            csv_row$is_fulltime <- job_time == "fulltime"
            csv_row$is_parttime <- FALSE
            csv_row$is_contract <- FALSE
            csv_row$is_internship <- FALSE

            t <- str_extract(job_desc, REGEX_JOB_TIME)
            if (!is.na(t))
            {
              if (str_detect(t, "Part")) csv_row$is_parttime <- TRUE
              if (str_detect(t, "Contract")) csv_row$is_contract <- TRUE
              if (str_detect(t, "Intern")) csv_row$is_internship <- TRUE
              job_desc <- str_remove_all(job_desc, REGEX_JOB_TIME)
            }

            # parse salary
            t <- str_match(job_desc, REGEX_SALARY_RANGE)
            if (3 <= ncol(t) && !is.na(t[1,1:3]))
            {
              csv_row$salary_min <- strtoi(str_remove_all(t[1,2], ","))
              csv_row$salary_max <- strtoi(str_remove_all(t[1,3], ","))
              job_desc <- str_remove_all(job_desc, REGEX_SALARY_RANGE)
            }

            # remove prefix
            job_desc <- str_replace(job_desc, "^Job details", "")

            # add remaining fields
            csv_row$job_location <- job_location
            csv_row$job_title <- str_replace(job_title, "\\+", " ")
            csv_row$job_id <- job_id
            csv_row$job_desc <- job_desc

            # add to csv
            i <- row_index
            df[i,] <<- csv_row
            row_index <<- row_index + 1
          }
  )

  write.csv(df, file = output_file, row.names = FALSE)
}


indeed_csv_build("Indeed_data\\merged.csv")
print('done')
```
