---
title: "R Notebook"
author: admin
date: 3/28/2021
output: html_document
---
```{r}
library(text2vec)
library(data.table)

data <- read.csv("Indeed_data\\merged.csv")
data$is_fulltime <- as.logical(data$is_fulltime)
data$is_contract <- as.logical(data$is_contract)
data$is_parttime <- as.logical(data$is_parttime)
data$is_internship <- as.logical(data$is_internship)
data$salary_min <- as.integer(data$salary_min)
data$salary_max <- as.integer(data$salary_max)
```
```{r}
data$to_parse <- rep(NA, nrow(data))

for (i in seq_len(nrow(data)))
{
  row <- data[i,]

  x <- paste(row$job_location, row$job_title, row$job_desc)
  if (row$is_fulltime) x <- paste(x, "fulltime full time ")
  if (row$is_parttime) x <- paste(x, "parttime part time ")
  if (row$is_internship) x <- paste(x, "internship ")
  if (row$is_contract) x <- paste(x, "contract ")

  row$to_parse <- x
  data[i,] <- row
}
```
```{r}
it <- itoken(
  data$to_parse,
  preprocessor = tolower,
  tokenizer = word_tokenizer,
  ids = data$job_id,
  progressbar = FALSE
)

stop_words <- c("a","an","and","are","as","at","be","by","for","from","have","in","is","i","not","of","on","or","other","our","ours","that","the","their","this","to","we","who","with","you","your","yours","me","my","myself","ourselves","")

vocab <- create_vocabulary(
        it,
        stopwords = stop_words,
        # ngram = c(1L, 2L)
)

tail(vocab, 5)

```
```{r}
vectorizer <- vocab_vectorizer(vocab)
dtm <- create_dtm(it, vectorizer)
print(dim(dtm))
```

# Create Cosine Dissimilarity Matrix
...and store it to CSV file.

```{r}
tfidf <- TfIdf$new()
dtm_tfidf <- fit_transform(dtm, tfidf)

cos_dissm <- sim2(
  x = dtm_tfidf,
  method = "cosine",
  norm = "l2"
)

cos_dissm[1:2, 1:5]

write.csv(
  as.matrix(cos_dissm),
  row.names = TRUE,
  file = gzfile("Indeed_data/cos_dissm_mat.csv.gz", "w+b")
)

```

# How to load:

```{r}
cos_dissm_2 <- read.csv(file = gzfile("Indeed_data/cos_dissm_mat.csv.gz"), stringsAsFactors = FALSE)
```